include $(SUBDIR)../config.mak

NAME = avsequencer
FFLIBS = avcodec avformat avutil

HEADERS = avsequencer.h \
          instr.h       \
          module.h      \
          order.h       \
          player.h      \
          sample.h      \
          song.h        \
          synth.h       \
          track.h       \

OBJS = allmixers.o      \
       avsequencer.o    \
       instr.o          \
       lq_mixer.o       \
       module.o         \
       order.o          \
       player.o         \
       sample.o         \
       song.o           \
       synth.o          \
       track.o          \

include $(SUBDIR)../subdir.mak
