include $(SUBDIR)../config.mak

NAME = avsequencer
FFLIBS = avcodec avformat avutil

HEADERS = avsequencer.h \
          module.h      \
          song.h        \
          order.h       \
          track.h       \
          instr.h       \
          sample.h      \
          synth.h       \
          player.h      \

OBJS = avsequencer.o    \
       module.o         \
       song.o           \
       order.o          \
       track.o          \
       instr.o          \
       sample.o         \
       synth.o          \

include $(SUBDIR)../subdir.mak
